version: '3'
services:
  app:
    image: messaging-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo/messaging-service
    ports:
      - 7000:7000
      - 35729:35729
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    ports:
      - 57017:27017
